### ISSUE TITLE
Instance isn't available

### ISSUE THREAD

**Issue by Alex89P** [nicolasmn/homebridge-hyperion-ng#1]
Hello,

I tried to add the instance-part like this:
{
    "accessory": "Hyperion",
    "name": "TV Backlight",
    "ambilight_name": "Ambilight",
    "priority": "100",
    "host": "192.168.178.97",
    "port": "19444",
    "instances": [
        {
            "name": "TVAmbilight",
            "instance": 1
        },
        {
            "name": "WLED_Sideboard_hinten",
            "instance": 2
        }
    ]
}

but it doesn't work in HomeKit - just the main instance is available.

**Comment by nicolasmn** [comment]
Hi, you only need to add additional instances other than the actual ambilight instance to the `instances` array. So if you have a setup like in the following screenshot only the second instance has to be added to the `instances` array (instance counting starts at 0).

<img width="530" alt="Bildschirmfoto 2021-04-28 um 11 44 33" src="https://user-images.githubusercontent.com/855244/116383874-8e4c2080-a817-11eb-8e82-bc86db660d6e.png">

The correct configuration for your setup is likely:
```json
{
  "accessory": "Hyperion",
  "name": "TV Backlight",
  "ambilight_name": "Ambilight",
  "priority": "100",
  "host": "192.168.178.97",
  "port": "19444",
  "instances": [
    {
      "name": "WLED_Sideboard_hinten",
      "instance": 1
    },
  ]
}
```

**Comment by Alex89P** [comment]
Here are my instances in Hyperion:
![Bildschirmfoto 2021-04-28 um 14 57 22](https://user-images.githubusercontent.com/60710462/116407526-2525d680-a832-11eb-8443-cf2cbea1a129.png)

I tried to change the configuration and also changed the name to call it without  underlines in the name "_"
![Bildschirmfoto 2021-04-28 um 12 14 59](https://user-images.githubusercontent.com/60710462/116407178-c9f3e400-a831-11eb-8eaa-f963462c2748.png)

but after a restart I can't see the new instance button. There is just one button for the main instance and the light control itself.
![Bildschirmfoto 2021-04-28 um 14 53 56](https://user-images.githubusercontent.com/60710462/116407202-cf512e80-a831-11eb-8b1e-c5b072734ce8.png)

**Comment by nicolasmn** [comment]
The configuration looks correct. Did you install the package from npm or directly from this repository via `npm i -g nicolasmn/homebridge-hyperion-ng`?

**Comment by Alex89P** [comment]
I installed the package with "npm i -g nicolasmn/homebridge-hyperion-ng" via the Homebridge UI

**Comment by nicolasmn** [comment]
Can you please confirm from the "Plugins"-Tab in Homebridge UI that the installed version is `homebridge-hyperion-ng v2.0.0`

**Comment by Alex89P** [comment]
I just reinstalled it via the UI after I removed it because there version was different. It is showing that there is a new version available:
![Bildschirmfoto 2021-04-28 um 15 43 59](https://user-images.githubusercontent.com/60710462/116414832-1ee72880-a839-11eb-915c-17359bb7035c.png)

When I restart HB without updating the Plugin I can see and toggle the new button (WLEDSideboard instance) in Homekit but not the main instance anymore - it isn't available in HK.

**Comment by Alex89P** [comment]
I think there's a bit of overlap on the Homebridge ad. There is also a Hyperion plugin from "mav2010", which has exactly the same name: https://www.npmjs.com/package/homebridge-hyperion-ng

Is something likely to collide here?

**Comment by nicolasmn** [comment]
Yes that seems to be the problem. Please remove any `homebridge-hyperion-ng` plugins you have installed and try to install this plugin via `npm i -g nicolasmn/homebridge-hyperion-ng` directly from the command line without using Homebridge UI

**Comment by Alex89P** [comment]
Ok I have to look how to do that because Homebridge is running in a Portainer Docker.

**Comment by Alex89P** [comment]
The same result directly from the Rpi console:
The inserted instance is displayed as a switch, but no longer the main instance.

**Comment by nicolasmn** [comment]
You have to change `ambilight_name` => `ambilightName` in your config, then it should work as expected

**Comment by Alex89P** [comment]
Sorry my fault. There was again the collision with the other plug-in and the different config. After I changed the name it works perfectly.

Thank you very much for your help!
